[global]
dataFrameSerialization = "legacy"

[server]
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
